### ISSUE TITLE
problem executing command

### ISSUE THREAD

**Issue by amirdahal04** [lenard123/Voting-System#3]
npm run dev
this command is throwing a lot of issues,

npm run development

> @ development C:\xampp\htdocs\Voting-System
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'C:\xampp\htdocs\Voting-System\node_modules\laravel-mix\setup\webpack.config.js'
Require stack:
- C:\xampp\htdocs\Voting-System\node_modules\webpack\bin\convert-argv.js
- C:\xampp\htdocs\Voting-System\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at requireConfig (C:\xampp\htdocs\Voting-System\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\xampp\htdocs\Voting-System\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\xampp\htdocs\Voting-System\node_modules\webpack\bin\convert-argv.js:102:15)
    at C:\xampp\htdocs\Voting-System\node_modules\webpack\bin\webpack.js:171:41
    at Object.Yargs.self.parse (C:\xampp\htdocs\Voting-System\node_modules\yargs\yargs.js:533:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\xampp\\htdocs\\Voting-System\\node_modules\\webpack\\bin\\convert-argv.js',
    'C:\\xampp\\htdocs\\Voting-System\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amir\AppData\Roaming\npm-cache\_logs\2020-03-04T04_09_08_290Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amir\AppData\Roaming\npm-cache\_logs\2020-03-04T04_09_08_474Z-debug.log

**Comment by lenard123** [comment]
@amirdahal04 have you run
"npm install" first?

**Comment by frankMagoba** [comment]
> @amirdahal04 have you run
> "npm install" first?

Yes

**Comment by frankMagoba** [comment]
npm install results to
> @ development /home/lin/projects/assignments/Voting-System
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/lin/projects/assignments/Voting-System/node_modules/laravel-mix/setup/webpack.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at requireConfig (/home/lin/projects/assignments/Voting-System/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/lin/projects/assignments/Voting-System/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/lin/projects/assignments/Voting-System/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/lin/projects/assignments/Voting-System/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/home/lin/projects/assignments/Voting-System/node_modules/yargs/yargs.js:533:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lin/.npm/_logs/2020-10-05T09_15_53_755Z-debug.log

**Comment by lenard123** [comment]
I now have included the compiled JS files.
So it is now optional to compile it yourself.
